sheets:
  orders:
    name: Sheet1
  products:
    name: Sheet2
  discounts:
    name: Sheet3
  abandoned_carts:
    name: AbandonedCarts
  uploads:
    name: UserUploads
hafez_quotes:
  - fa: حافظا در کنج فقر و خلوت عزلت\nیارم آن شمع است و باقی همه پروانه
    it: Hafez, nel angolo della povertà e della solitudine,\nIl mio amato è la candela, e gli altri sono falene.
  - fa: دل می‌رود ز دستم صاحب‌دلان خدا را\nدارید در دلم دل، ای بی‌خبر ز حالم
    it: Il mio cuore sfugge di mano, o anime gentili, per Dio,\nTenete il mio cuore nel vostro cuore, o ignari del mio stato.
  - fa: ساقی به نور باده برافروز جام ما\nمطرب بگو که کار جهان شد به کام ما
    it: Coppiere, accendi il nostro calice con la luce del vino,\nMusico, di’ che il mondo si è piegato al nostro volere.
  - fa: بر سر آنم که گر ز دست برآید\nدست به کاری زنم که خیر بماند
    it: Ho deciso che, se mi sarà possibile,\nFarò qualcosa che lasci un bene duraturo.